import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';
import Layout from '../components/Layout';

const Home: NextPage = () => {
    const user = useSession();

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout className="container flex flex-col items-center justify-center mx-auto">
                <div className="flex flex-col text-4xl md:text-5xl font-bold text-center pb-[2rem]">
                    <span>Manage your finances with </span>
                    <span className="text-green-500">
                        <span className="text-black dark:text-white">
                            Expense{' '}
                        </span>
                        Tracker
                    </span>
                </div>
                <div className="text-center text-xl sm:text-3xl md:text-2xl w-8/12 sm:w-7/12 font-light">
                    Track expenses and income to get an accurate and visual
                    representation of your expenditure.
                </div>
                <div className="flex pt-16">
                    {user?.data?.user ? (
                        <>
                            <Link href="/expenses">
                                <button className="btn btn-primary">
                                    My Expenses
                                </button>
                            </Link>
                        </>
                    ) : (
                        <div className="flex flex-col items-center">
                            <Link href="/signin">
                                <button className="btn btn-primary">
                                    Get Started
                                </button>
                            </Link>
                            <Link href="/learn-more">
                                <span className="text-blue-400 pt-4 sm:text-lg">
                                    Learn more
                                </span>
                            </Link>
                        </div>
                    )}
                </div>
            </Layout>
        </>
    );
};

export default Home;
